
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComicWS", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/ComicWS/ComicWS?wsdl")
public class ComicWS_Service
    extends Service
{

    private final static URL COMICWS_WSDL_LOCATION;
    private final static WebServiceException COMICWS_EXCEPTION;
    private final static QName COMICWS_QNAME = new QName("http://ws/", "ComicWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ComicWS/ComicWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMICWS_WSDL_LOCATION = url;
        COMICWS_EXCEPTION = e;
    }

    public ComicWS_Service() {
        super(__getWsdlLocation(), COMICWS_QNAME);
    }

    public ComicWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMICWS_QNAME, features);
    }

    public ComicWS_Service(URL wsdlLocation) {
        super(wsdlLocation, COMICWS_QNAME);
    }

    public ComicWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMICWS_QNAME, features);
    }

    public ComicWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComicWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComicWS
     */
    @WebEndpoint(name = "ComicWSPort")
    public ComicWS getComicWSPort() {
        return super.getPort(new QName("http://ws/", "ComicWSPort"), ComicWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComicWS
     */
    @WebEndpoint(name = "ComicWSPort")
    public ComicWS getComicWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ComicWSPort"), ComicWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMICWS_EXCEPTION!= null) {
            throw COMICWS_EXCEPTION;
        }
        return COMICWS_WSDL_LOCATION;
    }

}
