
package ws;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSSerie", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSSerie {


    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "remove", targetNamespace = "http://ws/", className = "ws.Remove")
    @Action(input = "http://ws/WSSerie/remove")
    public void remove(
        @WebParam(name = "entity", targetNamespace = "")
        Serie entity);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://ws/", className = "ws.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://ws/", className = "ws.CountResponse")
    @Action(input = "http://ws/WSSerie/countRequest", output = "http://ws/WSSerie/countResponse")
    public int count();

    /**
     * 
     * @param id
     * @return
     *     returns ws.Serie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://ws/", className = "ws.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://ws/", className = "ws.FindResponse")
    @Action(input = "http://ws/WSSerie/findRequest", output = "http://ws/WSSerie/findResponse")
    public Serie find(
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "create", targetNamespace = "http://ws/", className = "ws.Create")
    @Action(input = "http://ws/WSSerie/create")
    public void create(
        @WebParam(name = "entity", targetNamespace = "")
        Serie entity);

    /**
     * 
     * @param range
     * @return
     *     returns java.util.List<ws.Serie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRange", targetNamespace = "http://ws/", className = "ws.FindRange")
    @ResponseWrapper(localName = "findRangeResponse", targetNamespace = "http://ws/", className = "ws.FindRangeResponse")
    @Action(input = "http://ws/WSSerie/findRangeRequest", output = "http://ws/WSSerie/findRangeResponse")
    public List<Serie> findRange(
        @WebParam(name = "range", targetNamespace = "")
        List<Integer> range);

    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "edit", targetNamespace = "http://ws/", className = "ws.Edit")
    @Action(input = "http://ws/WSSerie/edit")
    public void edit(
        @WebParam(name = "entity", targetNamespace = "")
        Serie entity);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Serie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ws/", className = "ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ws/", className = "ws.FindAllResponse")
    @Action(input = "http://ws/WSSerie/findAllRequest", output = "http://ws/WSSerie/findAllResponse")
    public List<Serie> findAll();

}
