
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSSerie", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/WSSerie/WSSerie?wsdl")
public class WSSerie_Service
    extends Service
{

    private final static URL WSSERIE_WSDL_LOCATION;
    private final static WebServiceException WSSERIE_EXCEPTION;
    private final static QName WSSERIE_QNAME = new QName("http://ws/", "WSSerie");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSSerie/WSSerie?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERIE_WSDL_LOCATION = url;
        WSSERIE_EXCEPTION = e;
    }

    public WSSerie_Service() {
        super(__getWsdlLocation(), WSSERIE_QNAME);
    }

    public WSSerie_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERIE_QNAME, features);
    }

    public WSSerie_Service(URL wsdlLocation) {
        super(wsdlLocation, WSSERIE_QNAME);
    }

    public WSSerie_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERIE_QNAME, features);
    }

    public WSSerie_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSerie_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSSerie
     */
    @WebEndpoint(name = "WSSeriePort")
    public WSSerie getWSSeriePort() {
        return super.getPort(new QName("http://ws/", "WSSeriePort"), WSSerie.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSerie
     */
    @WebEndpoint(name = "WSSeriePort")
    public WSSerie getWSSeriePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "WSSeriePort"), WSSerie.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERIE_EXCEPTION!= null) {
            throw WSSERIE_EXCEPTION;
        }
        return WSSERIE_WSDL_LOCATION;
    }

}
