
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSVinieta", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/WSVinieta/WSVinieta?wsdl")
public class WSVinieta_Service
    extends Service
{

    private final static URL WSVINIETA_WSDL_LOCATION;
    private final static WebServiceException WSVINIETA_EXCEPTION;
    private final static QName WSVINIETA_QNAME = new QName("http://ws/", "WSVinieta");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSVinieta/WSVinieta?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSVINIETA_WSDL_LOCATION = url;
        WSVINIETA_EXCEPTION = e;
    }

    public WSVinieta_Service() {
        super(__getWsdlLocation(), WSVINIETA_QNAME);
    }

    public WSVinieta_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSVINIETA_QNAME, features);
    }

    public WSVinieta_Service(URL wsdlLocation) {
        super(wsdlLocation, WSVINIETA_QNAME);
    }

    public WSVinieta_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSVINIETA_QNAME, features);
    }

    public WSVinieta_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSVinieta_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSVinieta
     */
    @WebEndpoint(name = "WSVinietaPort")
    public WSVinieta getWSVinietaPort() {
        return super.getPort(new QName("http://ws/", "WSVinietaPort"), WSVinieta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSVinieta
     */
    @WebEndpoint(name = "WSVinietaPort")
    public WSVinieta getWSVinietaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "WSVinietaPort"), WSVinieta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSVINIETA_EXCEPTION!= null) {
            throw WSVINIETA_EXCEPTION;
        }
        return WSVINIETA_WSDL_LOCATION;
    }

}
